env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "iM6IP3NULytwcnb4oLbBW7eJfykKs5NOYAjtOZQRjuIYp3RT/RShX+AWeilGmAZFiyWbgOXI0zY2AZ6VpTLncQaj/p0FhOeoWS2Y+di9/HU4/cYWPg8whukq6Kv6wlV33079RI/8XPvh/ukDld6MM6LTjfPbR0YT8Eag5kNb6LXOvYZOG7NL3qZdj/TBN1PXW4Dd712oEUFarGrYOG7ICJW/z90lF/SHzZ+KveN1OHu0tI2Uo8vGU/phLEKP+vGtPn5Pa5XJ6/bkkK0wY53aYjnU11lAi0cNrOutpwUFWxFBY4z0YgZa0WyB/eJlt49XnSJv3w9k4e0YZtF2KvISLzqWHc5SefOTNTlZoiX5cz2w3nhxQ5KI2dKrel3zi5hit0W+Bo5uJH9NnVr/Hw9t7TcHz0QxV9hW6OGN/5ScZSJZcGSqiTrW5v05qeW1NJHKPAc4Tg/PuoA7k75JLf9Jz25QcbGepAbIziP4toJmnUTKlOPdS+twMA1IFW4DIOPspiN2oLNbMjZPP7sDOeNVWB/9+MtxpoGgkfNNxu6Prl0eKHdkZLudkyRbh3Mnv2ndy/ec48P7rlb9bzYRmAEnPh+IRYl+79xNgUF5KCu36iO23pPYC/Z0yVYooSZtYAdnYegeKN2cCT4Iw+6c33xb4ZXJ8vaOPEihSwzTfngU7a8="

addons:
  coverity_scan:
    project:
      name: "saveman/octargs"
      description: "C++ command line argument parsing library"
    notification_email: k.kapuscik@gmail.com
    build_command_prepend: "/usr/bin/cmake -DCMAKE_BUILD_TYPE=Release ."
    build_command: "/usr/bin/cmake --build ."
    branch_pattern: coverity_scan

jobs:
  include:
    - name: Linux GCC
      os: linux
      dist: bionic
      language: cpp
      compiler: gcc
      before_install:
        - bash ./scripts/travis-linux-before_install.sh
      before_script:
        - bash ./scripts/travis-linux-before_script.sh
      script:
        - bash ./scripts/travis-linux-script.sh

    - name: Linux CLANG
      os: linux
      dist: bionic
      language: cpp
      compiler: clang
      before_install:
        - bash ./scripts/travis-linux-before_install.sh
      before_script:
        - bash ./scripts/travis-linux-before_script.sh
      script:
        - bash ./scripts/travis-linux-script.sh

    - name: Windows
      os: windows
      language: cpp
      filter_secrets: false
      before_install:
        - choco install nsis
      script:
        - ./scripts/travis-windows-script.bat
