language: cpp

os:
  - linux

dist:
  - bionic

compiler:
  - gcc
  - clang

before_install:
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
  - sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ bionic main"
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo dpkg -L cmake
  - sudo cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/../install -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cd build
  - make
  - make install
  - ctest
