language: cpp

os:
  - linux

dist:
  - bionic

compiler:
  - gcc
  - clang

before_install:
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
  - sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ bionic main"
  - sudo apt-get -y update
  - sudo apt-get -y install cmake libcppunit-dev

before_script:
  - rm -rf build
  - rm -rf install
  - mkdir -p build
  - cd build
  - /usr/bin/cmake --version
  - /usr/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/../install -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cd build
  - /usr/bin/cmake --build .
  - /usr/bin/cmake --build . -- install
  - /usr/bin/cmake --build . -- test
