language: cpp

os:
  - linux

dist:
  - bionic

compiler:
  - gcc
  - clang

before_install:
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
  - sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ bionic main"
  - sudo apt-get update
  - sudo apt-get install cmake

before_script:
  - mkdir build
  - cd build
  - which cmake
  - cmake --version
  - /usr/bin/cmake --version
  - /usr/bin/cmake -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/../install -DCMAKE_BUILD_TYPE=Debug ..

script:
  - cd build
  - cmake --build .
  - cmake --build . -- install
  - cmake --build . -- test
